# For a full list of rules, go to https://docs.astral.sh/ruff/rules/

line-length = 100
target-version = "py310"
fix = true

[lint]
extend-select = [
    "A",
    "ASYNC",
    "B007",
    "C4",
    "D2",
    "D4",
    "E",
    "FAST",
    "FLY",
    "FURB",
    "I",
    "ISC",
    "N",
    "PIE",
    "PT",
    "RET501",
    "RUF",
    "T20",
    "UP",
    "W",
]

ignore = [
    "F403",
    "D205",
    "PIE796",
    "N818",
    "A003",
    "RUF012",
    "D401",
    "RUF005",
]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"examples/*" = ["T201"]
